package cc.chli.vc.model;

public class Alliance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alliance.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance.id
     *
     * @return the value of alliance.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance.id
     *
     * @param id the value for alliance.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alliance.name
     *
     * @return the value of alliance.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alliance.name
     *
     * @param name the value for alliance.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}