package cc.chli.vc.model;

public class Permissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.permission
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.specialID
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private Integer specialid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions.type
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.id
     *
     * @return the value of permissions.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.id
     *
     * @param id the value for permissions.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.name
     *
     * @return the value of permissions.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.name
     *
     * @param name the value for permissions.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.permission
     *
     * @return the value of permissions.permission
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.permission
     *
     * @param permission the value for permissions.permission
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.specialID
     *
     * @return the value of permissions.specialID
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public Integer getSpecialid() {
        return specialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.specialID
     *
     * @param specialid the value for permissions.specialID
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setSpecialid(Integer specialid) {
        this.specialid = specialid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions.type
     *
     * @return the value of permissions.type
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions.type
     *
     * @param type the value for permissions.type
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}