package cc.chli.vc.model;

public class PermissionsGroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_group.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_group.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permissions_group.permissionsGroup
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    private String permissionsgroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_group.id
     *
     * @return the value of permissions_group.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions_group.id
     *
     * @param id the value for permissions_group.id
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_group.name
     *
     * @return the value of permissions_group.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions_group.name
     *
     * @param name the value for permissions_group.name
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permissions_group.permissionsGroup
     *
     * @return the value of permissions_group.permissionsGroup
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public String getPermissionsgroup() {
        return permissionsgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permissions_group.permissionsGroup
     *
     * @param permissionsgroup the value for permissions_group.permissionsGroup
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    public void setPermissionsgroup(String permissionsgroup) {
        this.permissionsgroup = permissionsgroup;
    }
}