package cc.chli.vc.dao;

import cc.chli.vc.model.AllianceMember;
import cc.chli.vc.model.AllianceMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllianceMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    long countByExample(AllianceMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int deleteByExample(AllianceMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int insert(AllianceMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int insertSelective(AllianceMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    List<AllianceMember> selectByExample(AllianceMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    AllianceMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") AllianceMember record, @Param("example") AllianceMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByExample(@Param("record") AllianceMember record, @Param("example") AllianceMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByPrimaryKeySelective(AllianceMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance_member
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByPrimaryKey(AllianceMember record);
}