package cc.chli.vc.dao;

import cc.chli.vc.model.Alliance;
import cc.chli.vc.model.AllianceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AllianceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    long countByExample(AllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int deleteByExample(AllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int insert(Alliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int insertSelective(Alliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    List<Alliance> selectByExample(AllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    Alliance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByExampleSelective(@Param("record") Alliance record, @Param("example") AllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByExample(@Param("record") Alliance record, @Param("example") AllianceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByPrimaryKeySelective(Alliance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alliance
     *
     * @mbg.generated Sun Aug 06 13:05:17 CST 2017
     */
    int updateByPrimaryKey(Alliance record);
}